apiVersion: apps/v1
kind: Deployment
metadata:
    name: gke-prism
    namespace: reactapp
    labels:
      app: reactapp
spec:
    replicas: 3
    selector:
        matchLabels:
            app: reactapp
    template:
        metadata:
            labels:
                app: reactapp
        spec:
            containers:
            - name: reactapp
              image: gcr.io/PROJECT_ID/IMAGE:TAG
              ports:
              - containerPort: 3000