apiVersion: v1
kind: Namespace
metadata:
    name: reactapp
---
apiVersion: v1
kind: Service
metadata:
    name: reactapp
    namespace: reactapp
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000
    selector:
        app: reactapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: reactapp
    namespace: reactapp
    labels:
      app: reactapp
spec:
    replicas: 3
    selector:
        matchLabels:
            app: reactapp
    template:
        metadata:
            labels:
                app: reactapp
        spec:
            containers:
            - name: reactapp
              image: gcr.io/PROJECT_ID/IMAGE:TAG
              ports:
              - containerPort: 3000