apiVersion: v1
kind: Service
metadata:
    name: reactapp
    namespace: reactapp
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000
    selector:
        app: reactapp